### ISSUE TITLE
Could there be an option for the user to change the shortcut from "Alt+Z"?

### ISSUE THREAD

**Issue by Jane5792** [mauforonda/context#1]
Hello,
I quite like the Context extension, it is a great boon for quickly comprehending or exploring the content of whatever you are reading.
However, I use the "Alt+Z" shortcut for a different macro and was wondering if you could add the option to change the shortcut the Context extension uses?

**Comment by mauforonda** [comment]
Hi, Firefox actually lets you change the keyboard shortcut [on about:addons](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox). 

![image](https://user-images.githubusercontent.com/4010711/125883755-b01fe595-804e-4516-bea4-0980451fcc01.png)

Thanks for enjoying the extension, your comment made my day :smile:
